version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hey There'
            echo 'This is the delivery pipeline from Shreyas'
      - run:
          name: Code has arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Running in a Unique Container
          command: |
            node -v